name = "uaflex"
description = "Unicode-aware lexical analyzer generator for Ada, similar to lex."
version = "3.0.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/uaflex"
tags = ["flex", "parser", "generator", "grammar", "analysis", "scanner", "lexer"]
executables = ["uaflex"]

[build-switches]
"*".Ada_Version = "Ada2022"
development.optimization = ["-O0"]
development.style_checks = ["-gnaty", "-gnaty-B"]
development.contracts = "Yes"
"*".debug_info = "Yes"

[[actions]]
type = "test"
command = ["alr", "-C" , "testsuite", "run"]

[[actions]]
type = "test"
command = ["echo", "alr", "-C" , "testsuite", "run"]

[[depends-on]]
gnat_native = "<16"

[[depends-on]]
vss_extra = "^26.2.0"
